spring.datasource.url: jdbc:mysql://localhost:3306/sge
spring.datasource.username: sge_user
spring.datasource.password: javaee
spring.jpa.databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect

spring.jpa.properties.javax.persistence.schema-generation.database.action: none #drop-and-create
spring.jpa.open-in-view: false


server.servlet.context-path: /sge-api
server.port: 12021