spring.datasource.url: jdbc:mysql://localhost:3306/sge?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username: sge_user
spring.datasource.password: javaee
spring.jpa.databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect

spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create
spring.jpa.open-in-view: false

server.servlet.context-path: /sge-api
rest.base-path: /rest

server.port: 12021

spring:  mvc:    view:      prefix: /WEB-INF/jsp/      suffix: .jsp    static-path-pattern: /resources/** 